Feature/deleted application list
ms-club-sliit/msclub-admin-panel pull request #145
Opened 2022-02-06 07:36 UTC by Shehanx86

2022-02-06 07:46 UTC, Shehanx86 commented
1. Deleted applications list page created
2. retrieving deleted (archive) application list bug fixed

2022-02-06 08:38 UTC, KaveenLaksitha approved these changes

2022-02-06 10:17 UTC, KaveenLaksitha requested changes
please remove comments

2022-02-07 04:00 UTC, senuravihanjayadeva requested changes

2022-02-07 09:21 UTC, Shehanx86 commented on src/store/api/ApplicationAPI.ts
> +	static getArchiveApplications(): Promise<IApplication[]> {
on it

2022-02-07 10:35 UTC, senuravihanjayadeva approved these changes

2022-02-07 11:04 UTC, merged