Implement permanent delete for inquiry
ms-club-sliit/msclub-admin-panel pull request #176
Opened 2022-02-20 04:38 UTC by ChathurikaThathsarani

2022-02-20 04:46 UTC, miyurugunarathna requested changes

2022-02-20 04:46 UTC, miyurugunarathna commented on src/pages/inquiry/permanent-delete/index.tsx
> +	const closeModal = () => {
When we close the modal. It's good to unset the selected id.

2022-02-20 05:35 UTC, miyurugunarathna approved these changes
LGTM

2022-02-21 12:15 UTC, senuravihanjayadeva approved these changes

2022-02-21 12:15 UTC, merged