Feature/delete permenently top speaker
ms-club-sliit/msclub-admin-panel pull request #185
Opened 2022-02-26 19:48 UTC by dilafar

2022-02-27 11:40 UTC, KaveenLaksitha requested changes
Please check the spelling of the word "Permanent".

2022-02-27 14:25 UTC, rusiruavb approved these changes
LGTM

2022-02-28 02:06 UTC, senuravihanjayadeva requested changes

2022-02-28 02:06 UTC, senuravihanjayadeva commented on src/store/top-speaker-store/topSpeakerActions.ts
> +		type: topSpeakerActionTypes.PERMANENT_DELETE_TOP_SPEAKER,
Can we use the DELETE_TOP_SPEAKER action type. Refer Event Actions

2022-02-28 02:06 UTC, senuravihanjayadeva commented on src/store/top-speaker-store/topSpeakerActions.ts
> +		type: topSpeakerActionTypes.PERMANENT_DELETE_TOP_SPEAKER,
And do the rest of the modifications

2022-02-28 02:06 UTC, senuravihanjayadeva commented on src/store/top-speaker-store/topSpeakerReducer.ts
> +	permanentDeletedTopSpeaker: null,
No need you can use deletedTopSpeaker

2022-02-28 02:06 UTC, senuravihanjayadeva commented on src/store/top-speaker-store/topSpeakerReducer.ts
> +		case `${TopSpeakerActionTypes.PERMANENT_DELETE_TOP_SPEAKER}_PENDING`:
No need

2022-02-28 02:06 UTC, senuravihanjayadeva commented on src/store/top-speaker-store/topSpeakerReducer.ts
> +		case `${TopSpeakerActionTypes.PERMANENT_DELETE_TOP_SPEAKER}_FULFILLED`:
No need

2022-02-28 02:06 UTC, senuravihanjayadeva commented on src/store/top-speaker-store/topSpeakerReducer.ts
> +		case `${TopSpeakerActionTypes.PERMANENT_DELETE_TOP_SPEAKER}_REJECTED`:
No need

2022-02-28 02:06 UTC, senuravihanjayadeva commented on src/pages/top-speaker/permenent-delete/index.tsx
> +	}, [state.permanentDeletedTopSpeaker, dispatch]);
state.permanentDeletedTopSpeaker -> state.deletedTopSpeaker

2022-02-28 02:06 UTC, senuravihanjayadeva commented on src/interfaces/ITopSpeaker.ts
> +	permanentDeletedTopSpeaker: ITopSpeaker | null;
No need

2022-03-01 02:04 UTC, merged