Translation en-US added
ms-club-sliit/msclub-admin-panel pull request #193
Opened 2022-03-02 09:27 UTC by nuduja

2022-03-02 10:05 UTC, miyurugunarathna commented on src/locales/en-US/translation.json
> +
Remove this unwanted space.

2022-03-03 10:40 UTC, rusiruavb requested changes

2022-03-03 10:40 UTC, rusiruavb commented on src/locales/en-US/translation.json
> +{
Can we use JavaScript object to store all the translations. Something like below. Then we can access the key values easily I guess. @senuravihanjayadeva @miyurugunarathna @nisalrenuja please give your ideas as well.
```
{
   translation: {
      button: {
         cancel: "Cancel"
         submit: "Submit"
      }
   }
}
```

2022-03-03 10:41 UTC, rusiruavb commented
@nuduja resolve the conflicts 😊

2022-03-10 01:57 UTC, closed without merging