Implemented inquires to display delete and edit buttons only for ADMIN and ROOT ADMIN
ms-club-sliit/msclub-admin-panel pull request #194
Opened 2022-03-02 14:08 UTC by SasinduNanayakkara

2022-03-03 03:52 UTC, KaveenLaksitha approved these changes
LGTM

2022-03-03 04:56 UTC, miyurugunarathna approved these changes
LGTM

2022-03-03 10:33 UTC, rusiruavb requested changes

2022-03-10 05:57 UTC, senuravihanjayadeva approved these changes

2022-03-10 06:15 UTC, merged