Fix/recent application
ms-club-sliit/msclub-admin-panel pull request #239
Opened 2022-04-11 16:40 UTC by Randula98

![Screenshot 2022-04-11 220927](https://user-images.githubusercontent.com/85297495/162788834-562ce2bd-76c6-4663-936b-c8087445a007.png)

2022-04-11 19:14 UTC, ThusharaX commented on src/pages/dashboard/application_info/index.tsx
> +											studentName={application.name.split(" ")[0] + " " + application.name.split(" ")[1] + " ..."}
There is nothing wrong with the code, but there is another simple way to do this

`studentName={application.name.split(" ").slice(0, 2).join(" ") + " ..."};`

https://www.w3schools.com/jsref/jsref_slice_array.asp

2022-04-12 01:23 UTC, senuravihanjayadeva requested changes
Use proper name for PR

2022-04-12 01:24 UTC, senuravihanjayadeva reviewed
Assign the Project also

2022-04-12 05:06 UTC, ThusharaX approved these changes

2022-04-12 05:07 UTC, merged