Reply inquiries feature implemented ✅
ms-club-sliit/msclub-admin-panel pull request #243
Opened 2022-04-12 20:06 UTC by ThusharaX

![image](https://user-images.githubusercontent.com/47711719/163044173-5748d46f-ef7d-4981-bb96-300f069775bd.png)

![image](https://user-images.githubusercontent.com/47711719/163044242-8144d062-33f3-4fb7-9d89-adf66cac3cde.png)

![image](https://user-images.githubusercontent.com/47711719/163044302-afeb242e-cd51-40e9-bd95-b67a18b213f5.png)

![image](https://user-images.githubusercontent.com/47711719/163044335-bc5a0791-8bd7-4695-8a11-31b8896247e5.png)

2022-04-12 20:48 UTC, miyurugunarathna approved these changes
LGTM

2022-04-13 03:18 UTC, senuravihanjayadeva requested changes

2022-04-13 03:18 UTC, senuravihanjayadeva commented on src/pages/inquiry/list/index.tsx
> +					<div className="dropdown-menu dropdown-menu-right" style={{ cursor: "pointer" }}>
Can we get rid of inline css

2022-04-13 08:19 UTC, senuravihanjayadeva approved these changes

2022-04-13 08:19 UTC, merged