Feature/get interview meeting details
ms-club-sliit/msclub-admin-panel pull request #268
Opened 2022-05-07 16:38 UTC by Avdunusinghe

2022-05-07 17:00 UTC, rusiruavb requested changes
@Avdunusinghe I have add a small change. Please take a 👀

2022-05-08 17:18 UTC, Avdunusinghe commented on src/interfaces/IApplication.ts
> +	sheduledLink: string;
Hello @rusiruavb 
It Fixed 
The backend service response result is also the same as this  spelling mistake

![image](https://user-images.githubusercontent.com/60811307/167307690-46602441-a5dc-4e17-a1ba-ffb8f53e3ec6.png)

2022-05-09 02:59 UTC, senuravihanjayadeva commented on src/interfaces/IApplication.ts
> +	sheduledLink: string;
Will Fix it

2022-05-11 02:54 UTC, senuravihanjayadeva approved these changes

2022-05-11 02:54 UTC, merged